<Project Sdk="Microsoft.NET.Sdk.Worker">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>dotnet-Shortener.Consumer-6b2ffd9b-dc1c-48a6-bb92-a84519726d16</UserSecretsId>
    <DockerDefaultTargetOS>Linux</DockerDefaultTargetOS>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Confluent.Kafka" Version="2.15.1" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="10.0.12" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Relational" Version="10.0.12" />
    <PackageReference Include="Microsoft.Extensions.Hosting" Version="10.0.12" />
    <PackageReference Include="Microsoft.VisualStudio.Azure.Containers.Tools.Targets" Version="1.24.2-preview.1" />
    <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="10.0.3" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Shortener.Application\Shortener.Application.csproj" />
    <ProjectReference Include="..\Shortener.Data\Shortener.Data.csproj" />
    <ProjectReference Include="..\Shortener.Infrastructure\Shortener.Infrastructure.csproj" />
    <ProjectReference Include="..\Shortener.Repository\Shortener.Repository.csproj" />
    <ProjectReference Include="..\Shortener.Services\Shortener.Services.csproj" />
    <ProjectReference Include="..\Shortener.Shared\Shortener.Shared.csproj" />
  </ItemGroup>
</Project>
